# Generated by Django 4.2.21 on 2025-06-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationapikelio',
            name='password',
            field=models.CharField(help_text='Mot de passe (stocké en clair)', max_length=200),
        ),
    ]
