# Generated by Django 4.2.21 on 2025-07-10 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_configurationapikelio_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propositioncandidat',
            options={'ordering': ['-score_final', '-created_at'], 'verbose_name': 'Proposition de candidat', 'verbose_name_plural': 'Propositions de candidats'},
        ),
        migrations.AddField(
            model_name='propositioncandidat',
            name='score_final',
            field=models.IntegerField(default=0, help_text='Score final calculé (base + bonus)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
