# Generated by Django 4.2.21 on 2025-07-21 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_propositioncandidat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinterim',
            name='niveaux_validation_requis',
            field=models.IntegerField(default=3, help_text='Nombre de niveaux de validation requis (3 par défaut : N+1 → N+2 → N+3)'),
        ),
        migrations.CreateModel(
            name='RegleEscalade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('type_declencheur', models.CharField(choices=[('DELAI_VALIDATION', 'Délai de validation dépassé'), ('DELAI_REPONSE_CANDIDAT', 'Délai de réponse candidat dépassé'), ('WORKFLOW_BLOQUE', 'Workflow bloqué'), ('URGENCE_NON_TRAITEE', 'Urgence non traitée'), ('DEMANDE_ABANDONNEE', 'Demande abandonnée')], max_length=30)),
                ('delai_declenchement_heures', models.IntegerField(help_text='Délai en heures avant déclenchement', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8760)])),
                ('urgences_concernees', models.CharField(blank=True, help_text="Types d'urgence concernés (ex: 'ELEVEE,CRITIQUE')", max_length=50)),
                ('niveaux_validation_concernes', models.CharField(blank=True, help_text="Niveaux de validation concernés (ex: '1,2')", max_length=20)),
                ('type_action', models.CharField(choices=[('NOTIFICATION_MANAGER', 'Notifier le manager'), ('ESCALADE_NIVEAU_SUPERIEUR', 'Escalader au niveau supérieur'), ('ASSIGNATION_AUTOMATIQUE', 'Assignation automatique'), ('NOTIFICATION_RH', 'Notifier les RH'), ('NOTIFICATION_ADMIN', 'Notifier les administrateurs'), ('SUSPENSION_DEMANDE', 'Suspendre la demande')], max_length=30)),
                ('message_escalade_template', models.TextField(blank=True, help_text="Template du message d'escalade (peut contenir des variables)")),
                ('nb_max_escalades', models.IntegerField(default=3, help_text="Nombre maximum d'escalades pour cette règle", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('delai_entre_escalades_heures', models.IntegerField(default=24, help_text='Délai entre les escalades répétées', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nb_declenchements', models.IntegerField(default=0)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_escalade_creees', to='mainapp.profilutilisateur')),
                ('departements_concernes', models.ManyToManyField(blank=True, help_text='Départements concernés par cette règle', to='mainapp.departement')),
                ('destinataires_escalade', models.ManyToManyField(blank=True, help_text="Destinataires spécifiques pour l'escalade", to='mainapp.profilutilisateur')),
            ],
            options={
                'verbose_name': "Règle d'escalade",
                'verbose_name_plural': "Règles d'escalade",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEscalade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('statut_execution', models.CharField(choices=[('REUSSIE', 'Réussie'), ('ECHEC', 'Échec'), ('PARTIELLE', 'Partielle'), ('ANNULEE', 'Annulée')], max_length=15)),
                ('destinataires_notifies', models.JSONField(default=list, help_text='Liste des destinataires effectivement notifiés')),
                ('actions_executees', models.JSONField(default=list, help_text='Actions effectivement exécutées')),
                ('erreurs_rencontrees', models.JSONField(default=list, help_text="Erreurs rencontrées pendant l'exécution")),
                ('contexte_execution', models.JSONField(default=dict, help_text="Contexte au moment de l'exécution")),
                ('message_envoye', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalades_historique', to='mainapp.demandeinterim')),
                ('notification_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalade_origine', to='mainapp.notificationinterim')),
                ('regle_escalade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_executions', to='mainapp.regleescalade')),
            ],
            options={
                'verbose_name': 'Historique escalade',
                'verbose_name_plural': 'Historiques escalades',
                'ordering': ['-date_execution'],
            },
        ),
        migrations.CreateModel(
            name='DelegationTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_delegation', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_delegation', models.CharField(choices=[('COMPLETE', 'Délégation complète'), ('PARTIELLE', 'Délégation partielle'), ('URGENCE_SEULEMENT', 'Urgences seulement'), ('DEPARTEMENT_SPECIFIQUE', 'Département spécifique')], default='COMPLETE', max_length=25)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=15)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('niveau_validation_delegue', models.IntegerField(blank=True, help_text='Niveau de validation concerné (1=Responsable, 2=Directeur, 3=RH/Admin)', null=True)),
                ('urgences_concernees', models.CharField(blank=True, help_text="Types d'urgence concernés (ex: 'ELEVEE,CRITIQUE')", max_length=50)),
                ('montant_max_delegation', models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum autorisé (optionnel)', max_digits=10, null=True)),
                ('raison_delegation', models.TextField(help_text='Raison de la délégation (congés, maladie, mission, etc.)')),
                ('instructions_specifiques', models.TextField(blank=True, help_text='Instructions spécifiques pour le délégataire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nb_validations_effectuees', models.IntegerField(default=0)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('notifier_delegant', models.BooleanField(default=True, help_text='Notifier le délégant des validations effectuées')),
                ('notifier_fin_delegation', models.BooleanField(default=True, help_text='Notifier la fin de délégation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_creees', to='mainapp.profilutilisateur')),
                ('delegant', models.ForeignKey(help_text='Utilisateur qui délègue ses pouvoirs', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_donnees', to='mainapp.profilutilisateur')),
                ('delegataire', models.ForeignKey(help_text='Utilisateur qui reçoit la délégation', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to='mainapp.profilutilisateur')),
                ('departements_concernes', models.ManyToManyField(blank=True, help_text='Départements concernés par la délégation', to='mainapp.departement')),
            ],
            options={
                'verbose_name': 'Délégation temporaire',
                'verbose_name_plural': 'Délégations temporaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delegant', 'statut'], name='mainapp_del_delegan_9dee45_idx'), models.Index(fields=['delegataire', 'statut'], name='mainapp_del_delegat_7b9c5a_idx'), models.Index(fields=['date_debut', 'date_fin'], name='mainapp_del_date_de_11688f_idx')],
            },
        ),
    ]
