# Generated by Django 4.2.21 on 2025-08-06 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_alter_demandeinterim_niveaux_validation_requis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Competence', 'verbose_name_plural': 'Competences'},
        ),
        migrations.AlterModelOptions(
            name='competenceutilisateur',
            options={'ordering': ['-niveau_maitrise', 'competence__nom'], 'verbose_name': 'Competence utilisateur', 'verbose_name_plural': 'Competences utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='delegationtemporaire',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delegation temporaire', 'verbose_name_plural': 'Delegations temporaires'},
        ),
        migrations.AlterModelOptions(
            name='demandeinterim',
            options={'ordering': ['-created_at'], 'verbose_name': "Demande d'interim", 'verbose_name_plural': "Demandes d'interim"},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom'], 'verbose_name': 'Departement', 'verbose_name_plural': 'Departements'},
        ),
        migrations.AlterModelOptions(
            name='disponibiliteutilisateur',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Disponibilite utilisateur', 'verbose_name_plural': 'Disponibilites utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='notificationinterim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification interim', 'verbose_name_plural': 'Notifications interim'},
        ),
        migrations.AlterModelOptions(
            name='profilutilisateurextended',
            options={'verbose_name': 'Donnees etendues utilisateur', 'verbose_name_plural': 'Donnees etendues utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='profilutilisateurkelio',
            options={'verbose_name': 'Donnees Kelio utilisateur', 'verbose_name_plural': 'Donnees Kelio utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='regleescalade',
            options={'ordering': ['nom'], 'verbose_name': "Regle d'escalade", 'verbose_name_plural': "Regles d'escalade"},
        ),
        migrations.AlterModelOptions(
            name='reponsecandidatinterim',
            options={'ordering': ['-date_proposition'], 'verbose_name': 'Reponse candidat interim', 'verbose_name_plural': 'Reponses candidats interim'},
        ),
        migrations.AlterModelOptions(
            name='scoredetailcandidat',
            options={'ordering': ['-score_total'], 'verbose_name': 'Score detaille candidat', 'verbose_name_plural': 'Scores detailles candidats'},
        ),
        migrations.AlterModelOptions(
            name='workflowetape',
            options={'ordering': ['ordre'], 'verbose_name': 'Etape de workflow', 'verbose_name_plural': 'Etapes de workflow'},
        ),
        migrations.AlterField(
            model_name='competenceutilisateur',
            name='niveau_maitrise',
            field=models.IntegerField(choices=[(1, 'Debutant'), (2, 'Intermediaire'), (3, 'Confirme'), (4, 'Expert')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='competenceutilisateur',
            name='source_donnee',
            field=models.CharField(choices=[('LOCAL', 'Saisie locale'), ('KELIO', 'Importe Kelio'), ('MIXTE', 'Mixte')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='configurationapikelio',
            name='password',
            field=models.CharField(help_text='Mot de passe (stocke en clair)', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='bonus_chef_equipe',
            field=models.IntegerField(default=8, help_text="Bonus pour proposition par chef d'equipe (0-50 points)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='bonus_experience_similaire',
            field=models.IntegerField(default=8, help_text='Bonus pour experience similaire (0-50 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='bonus_recommandation',
            field=models.IntegerField(default=10, help_text='Bonus pour qualite de recommandation (0-50 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='configuration_par_defaut',
            field=models.BooleanField(default=False, help_text='Configuration utilisee par defaut'),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='nom',
            field=models.CharField(help_text="Nom de la configuration (ex: 'Defaut', 'Technique', 'Commercial')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='penalite_distance_excessive',
            field=models.IntegerField(default=10, help_text='Penalite pour distance excessive (0-100 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='penalite_indisponibilite_partielle',
            field=models.IntegerField(default=15, help_text='Penalite pour indisponibilite partielle (0-100 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='penalite_indisponibilite_totale',
            field=models.IntegerField(default=50, help_text='Penalite pour indisponibilite totale (0-100 points)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='poids_anciennete',
            field=models.FloatField(default=0.05, help_text="Poids pour l'anciennete (0.0 a 1.0)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='poids_competences',
            field=models.FloatField(default=0.25, help_text='Poids pour les competences (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='poids_disponibilite',
            field=models.FloatField(default=0.15, help_text='Poids pour la disponibilite (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='poids_experience',
            field=models.FloatField(default=0.2, help_text="Poids pour l'experience (0.0 a 1.0)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='poids_proximite',
            field=models.FloatField(default=0.1, help_text='Poids pour la proximite geographique (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='poids_similarite_poste',
            field=models.FloatField(default=0.25, help_text='Poids pour la similarite de poste (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='configurationscoring',
            name='pour_departements',
            field=models.ManyToManyField(blank=True, help_text='Departements autorises a utiliser cette configuration', to='mainapp.departement'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='delegant',
            field=models.ForeignKey(help_text='Utilisateur qui delegue ses pouvoirs', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_donnees', to='mainapp.profilutilisateur'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='delegataire',
            field=models.ForeignKey(help_text='Utilisateur qui recoit la delegation', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to='mainapp.profilutilisateur'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='departements_concernes',
            field=models.ManyToManyField(blank=True, help_text='Departements concernes par la delegation', to='mainapp.departement'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='instructions_specifiques',
            field=models.TextField(blank=True, help_text='Instructions specifiques pour le delegataire'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='montant_max_delegation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum autorise (optionnel)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='niveau_validation_delegue',
            field=models.IntegerField(blank=True, help_text='Niveau de validation concerne (1=Responsable, 2=Directeur, 3=RH/Admin)', null=True),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='notifier_delegant',
            field=models.BooleanField(default=True, help_text='Notifier le delegant des validations effectuees'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='notifier_fin_delegation',
            field=models.BooleanField(default=True, help_text='Notifier la fin de delegation'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='raison_delegation',
            field=models.TextField(help_text='Raison de la delegation (conges, maladie, mission, etc.)'),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='type_delegation',
            field=models.CharField(choices=[('COMPLETE', 'Delegation complete'), ('PARTIELLE', 'Delegation partielle'), ('URGENCE_SEULEMENT', 'Urgences seulement'), ('DEPARTEMENT_SPECIFIQUE', 'Departement specifique')], default='COMPLETE', max_length=25),
        ),
        migrations.AlterField(
            model_name='delegationtemporaire',
            name='urgences_concernees',
            field=models.CharField(blank=True, help_text="Types d'urgence concernes (ex: 'ELEVEE,CRITIQUE')", max_length=50),
        ),
        migrations.AlterField(
            model_name='demandeinterim',
            name='niveaux_validation_requis',
            field=models.IntegerField(default=3, help_text='Nombre de niveaux de validation requis (3 par defaut : N+1 -> N+2 -> N+3)'),
        ),
        migrations.AlterField(
            model_name='demandeinterim',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_PROPOSITION', 'En recherche/proposition candidats'), ('EN_VALIDATION', 'En validation'), ('CANDIDAT_PROPOSE', 'Candidat propose'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee'), ('REFUSEE', 'Refusee'), ('ANNULEE', 'Annulee')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeinterim',
            name='urgence',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevee'), ('CRITIQUE', 'Critique')], default='NORMALE', max_length=15),
        ),
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,10}$', 'Code departement invalide')]),
        ),
        migrations.AlterField(
            model_name='disponibiliteutilisateur',
            name='type_disponibilite',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible'), ('EN_MISSION', 'En mission'), ('CONGE', 'En conge'), ('FORMATION', 'En formation'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='action',
            field=models.CharField(choices=[('CREATION_DEMANDE', 'Creation demande'), ('MODIFICATION_DEMANDE', 'Modification demande'), ('PROPOSITION_CANDIDAT', 'Proposition candidat'), ('EVALUATION_CANDIDAT', 'Evaluation candidat'), ('VALIDATION_RESPONSABLE', 'Validation Responsable (N+1)'), ('VALIDATION_DIRECTEUR', 'Validation Directeur (N+2)'), ('VALIDATION_RH', 'Validation RH (Final)'), ('VALIDATION_ADMIN', 'Validation Admin (Final)'), ('VALIDATION_SUPERUSER', 'Validation Superutilisateur'), ('SELECTION_CANDIDAT', 'Selection candidat'), ('NOTIFICATION_CANDIDAT', 'Notification candidat'), ('REPONSE_CANDIDAT', 'Reponse candidat'), ('DEBUT_MISSION', 'Debut mission'), ('FIN_MISSION', 'Fin mission'), ('ANNULATION', 'Annulation'), ('COMMENTAIRE', 'Ajout commentaire')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historiqueescalade',
            name='actions_executees',
            field=models.JSONField(default=list, help_text='Actions effectivement executees'),
        ),
        migrations.AlterField(
            model_name='historiqueescalade',
            name='contexte_execution',
            field=models.JSONField(default=dict, help_text="Contexte au moment de l'execution"),
        ),
        migrations.AlterField(
            model_name='historiqueescalade',
            name='destinataires_notifies',
            field=models.JSONField(default=list, help_text='Liste des destinataires effectivement notifies'),
        ),
        migrations.AlterField(
            model_name='historiqueescalade',
            name='erreurs_rencontrees',
            field=models.JSONField(default=list, help_text="Erreurs rencontrees pendant l'execution"),
        ),
        migrations.AlterField(
            model_name='historiqueescalade',
            name='statut_execution',
            field=models.CharField(choices=[('REUSSIE', 'Reussie'), ('ECHEC', 'Echec'), ('PARTIELLE', 'Partielle'), ('ANNULEE', 'Annulee')], max_length=15),
        ),
        migrations.AlterField(
            model_name='motifabsence',
            name='categorie',
            field=models.CharField(choices=[('MALADIE', 'Maladie'), ('CONGE', 'Conge'), ('FORMATION', 'Formation'), ('PERSONNEL', 'Personnel'), ('PROFESSIONNEL', 'Professionnel')], default='PERSONNEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationinterim',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Metadonnees supplementaires pour les notifications'),
        ),
        migrations.AlterField(
            model_name='notificationinterim',
            name='statut',
            field=models.CharField(choices=[('NON_LUE', 'Non lue'), ('LUE', 'Lue'), ('TRAITEE', 'Traitee'), ('ARCHIVEE', 'Archivee')], default='NON_LUE', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationinterim',
            name='type_notification',
            field=models.CharField(choices=[('NOUVELLE_DEMANDE', "Nouvelle demande d'interim"), ('DEMANDE_A_VALIDER', 'Demande a valider'), ('PROPOSITION_CANDIDAT', 'Nouvelle proposition de candidat'), ('CANDIDAT_PROPOSE_VALIDATION', 'Candidat propose pour validation'), ('VALIDATION_EFFECTUEE', 'Validation effectuee'), ('CANDIDAT_SELECTIONNE', 'Candidat selectionne'), ('CANDIDAT_NOTIFIE', 'Candidat notifie'), ('CANDIDAT_ACCEPTE', 'Candidat a accepte'), ('CANDIDAT_REFUSE', 'Candidat a refuse'), ('MISSION_DEMARREE', 'Mission demarree'), ('MISSION_TERMINEE', 'Mission terminee'), ('RAPPEL_VALIDATION', 'Rappel de validation'), ('RETARD_WORKFLOW', 'Retard dans le workflow')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poste',
            name='niveau_responsabilite',
            field=models.IntegerField(choices=[(1, 'Execution'), (2, 'Maitrise'), (3, 'Cadre')], default=1, help_text='Niveau de responsabilite'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='kelio_sync_status',
            field=models.CharField(choices=[('JAMAIS', 'Jamais synchronise'), ('REUSSI', 'Synchronisation reussie'), ('PARTIEL', 'Synchronisation partielle'), ('ECHEC', 'Echec synchronisation')], default='JAMAIS', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='statut_employe',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('CONGE', 'En conge'), ('FORMATION', 'En formation'), ('ARRET', 'Arret maladie'), ('SUSPENDU', 'Suspendu'), ('DEMISSION', 'Demission'), ('LICENCIE', 'Licencie')], default='ACTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='type_profil',
            field=models.CharField(choices=[('UTILISATEUR', 'Utilisateur standard'), ('CHEF_EQUIPE', "Chef d'equipe"), ('RESPONSABLE', 'Responsable (N+1)'), ('DIRECTEUR', 'Directeur (N+2)'), ('RH', 'RH (Final)'), ('ADMIN', 'Administrateur (Final)')], default='UTILISATEUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Utilisateur Django associe', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='bonus_proposition_humaine',
            field=models.IntegerField(default=5, help_text='Bonus accorde selon le niveau hierarchique', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='competences_specifiques',
            field=models.TextField(blank=True, help_text='Competences specifiques du candidat pour ce poste'),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='experience_pertinente',
            field=models.TextField(blank=True, help_text='Experience pertinente du candidat'),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='niveau_validation_propose',
            field=models.IntegerField(default=1, help_text='Niveau de validation ou la proposition a ete faite'),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='score_final',
            field=models.IntegerField(default=0, help_text='Score final calcule (base + bonus)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='score_humain_ajuste',
            field=models.IntegerField(blank=True, help_text='Score ajuste par un validateur humain', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='source_proposition',
            field=models.CharField(choices=[('DEMANDEUR_INITIAL', 'Demandeur initial'), ('MANAGER_DIRECT', 'Manager direct'), ('CHEF_EQUIPE', "Chef d'equipe"), ('RESPONSABLE', 'Responsable (N+1)'), ('DIRECTEUR', 'Directeur (N+2)'), ('RH', 'RH (Final)'), ('ADMIN', 'Admin (Final)'), ('SUPERUSER', 'Superutilisateur'), ('VALIDATION_ETAPE', 'Ajout lors de validation'), ('SYSTEME', 'Systeme automatique'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propositioncandidat',
            name='statut',
            field=models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_EVALUATION', 'En evaluation'), ('EVALUEE', 'Evaluee'), ('RETENUE', 'Retenue pour validation'), ('REJETEE', 'Rejetee'), ('VALIDEE', 'Validee')], default='SOUMISE', max_length=15),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='delai_declenchement_heures',
            field=models.IntegerField(help_text='Delai en heures avant declenchement', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8760)]),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='delai_entre_escalades_heures',
            field=models.IntegerField(default=24, help_text='Delai entre les escalades repetees', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='departements_concernes',
            field=models.ManyToManyField(blank=True, help_text='Departements concernes par cette regle', to='mainapp.departement'),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='destinataires_escalade',
            field=models.ManyToManyField(blank=True, help_text="Destinataires specifiques pour l'escalade", to='mainapp.profilutilisateur'),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='nb_max_escalades',
            field=models.IntegerField(default=3, help_text="Nombre maximum d'escalades pour cette regle", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='niveaux_validation_concernes',
            field=models.CharField(blank=True, help_text="Niveaux de validation concernes (ex: '1,2')", max_length=20),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='type_action',
            field=models.CharField(choices=[('NOTIFICATION_MANAGER', 'Notifier le manager'), ('ESCALADE_NIVEAU_SUPERIEUR', 'Escalader au niveau superieur'), ('ASSIGNATION_AUTOMATIQUE', 'Assignation automatique'), ('NOTIFICATION_RH', 'Notifier les RH'), ('NOTIFICATION_ADMIN', 'Notifier les administrateurs'), ('SUSPENSION_DEMANDE', 'Suspendre la demande')], max_length=30),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='type_declencheur',
            field=models.CharField(choices=[('DELAI_VALIDATION', 'Delai de validation depasse'), ('DELAI_REPONSE_CANDIDAT', 'Delai de reponse candidat depasse'), ('WORKFLOW_BLOQUE', 'Workflow bloque'), ('URGENCE_NON_TRAITEE', 'Urgence non traitee'), ('DEMANDE_ABANDONNEE', 'Demande abandonnee')], max_length=30),
        ),
        migrations.AlterField(
            model_name='regleescalade',
            name='urgences_concernees',
            field=models.CharField(blank=True, help_text="Types d'urgence concernes (ex: 'ELEVEE,CRITIQUE')", max_length=50),
        ),
        migrations.AlterField(
            model_name='reponsecandidatinterim',
            name='motif_refus',
            field=models.CharField(blank=True, choices=[('INDISPONIBLE', 'Indisponible'), ('COMPETENCES', 'Competences insuffisantes'), ('DISTANCE', 'Trop eloigne'), ('REMUNERATION', 'Remuneration insuffisante'), ('PERSONNEL', 'Raisons personnelles'), ('CONFLIT_HORAIRES', "Conflit d'horaires"), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reponsecandidatinterim',
            name='reponse',
            field=models.CharField(choices=[('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse'), ('EN_ATTENTE', 'En attente de reponse'), ('EXPIRE', 'Expire')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='scoredetailcandidat',
            name='bonus_hierarchique',
            field=models.IntegerField(default=0, help_text='Bonus selon le niveau hierarchique du proposant'),
        ),
        migrations.AlterField(
            model_name='scoredetailcandidat',
            name='proposition_humaine',
            field=models.ForeignKey(blank=True, help_text="Reference si c'est une proposition humaine", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_candidat', to='mainapp.propositioncandidat'),
        ),
        migrations.AlterField(
            model_name='site',
            name='pays',
            field=models.CharField(default="Cote d'Ivoire", max_length=50),
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='candidats_rejetes',
            field=models.JSONField(default=list, help_text='Liste des candidats rejetes avec raisons'),
        ),
        migrations.AlterField(
            model_name='validationdemande',
            name='decision',
            field=models.CharField(choices=[('APPROUVE', 'Approuve'), ('APPROUVE_AVEC_MODIF', 'Approuve avec modifications'), ('REFUSE', 'Refuse'), ('REPORTE', 'Reporte'), ('CANDIDAT_AJOUTE', 'Candidat ajoute')], max_length=25),
        ),
        migrations.AlterField(
            model_name='workflowetape',
            name='condition_urgence',
            field=models.CharField(choices=[('TOUTES', 'Toutes'), ('NORMALE', 'Normale'), ('ELEVEE', 'Elevee'), ('CRITIQUE', 'Critique')], default='TOUTES', max_length=15),
        ),
        migrations.AlterField(
            model_name='workflowetape',
            name='type_etape',
            field=models.CharField(choices=[('DEMANDE', 'Creation de demande'), ('PROPOSITION_CANDIDATS', 'Proposition de candidats'), ('VALIDATION_RESPONSABLE', 'Validation Responsable (N+1)'), ('VALIDATION_DIRECTEUR', 'Validation Directeur (N+2)'), ('VALIDATION_RH_ADMIN', 'Validation RH/Admin (Final)'), ('NOTIFICATION_CANDIDAT', 'Notification candidat'), ('ACCEPTATION_CANDIDAT', 'Acceptation candidat'), ('FINALISATION', 'Finalisation')], max_length=30),
        ),
    ]
