# Generated by Django 4.2.21 on 2025-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_competence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationinterim',
            name='statut_lecture',
            field=models.CharField(choices=[('NON_LUE', 'Non lue'), ('LUE', 'Lue'), ('TRAITEE', 'Traitee'), ('ARCHIVEE', 'Archivee')], default='NON_LUE', max_length=15),
        ),
    ]
