# Generated by Django 4.2.21 on 2025-12-27 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_notificationinterim_statut_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleJourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique (ex: nouvel_an, tabaski)', max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_ferie', models.CharField(choices=[('FERIE_CHRETIEN', 'Férié chrétien'), ('FERIE_MUSULMAN', 'Férié musulman'), ('FERIE_CIVIL', 'Férié civil'), ('FERIE_INTERNE', 'Férié interne'), ('FERIE_AUTRE', 'Autre')], default='FERIE_CIVIL', max_length=20, verbose_name='Type de férié')),
                ('methode_calcul', models.CharField(choices=[('FIXE', 'Date fixe'), ('PAQUES', 'Basé sur Pâques'), ('HIJRI', 'Calendrier Hijri'), ('MANUEL', 'Manuel')], default='FIXE', max_length=20, verbose_name='Méthode de calcul')),
                ('mois_fixe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois (date fixe)')),
                ('jour_fixe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour (date fixe)')),
                ('decalage_paques', models.SmallIntegerField(blank=True, null=True, verbose_name='Décalage Pâques (jours)')),
                ('mois_hijri', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois Hijri')),
                ('jour_hijri', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Jour Hijri')),
                ('est_national', models.BooleanField(default=True, verbose_name='Férié national')),
                ('est_paye', models.BooleanField(default=True, verbose_name='Jour chômé payé')),
                ('est_modifiable', models.BooleanField(default=False, verbose_name='Date modifiable')),
                ('est_systeme', models.BooleanField(default=False, verbose_name='Modèle système')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('code_pays', models.CharField(default='CI', max_length=2, verbose_name='Code pays')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de jour férié',
                'verbose_name_plural': 'Modèles de jours fériés',
                'db_table': 'modeles_jours_feries',
                'ordering': ['mois_fixe', 'jour_fixe', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('date_ferie', models.DateField(verbose_name='Date du férié')),
                ('date_calculee', models.DateField(blank=True, null=True, verbose_name='Date calculée')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_ferie', models.CharField(choices=[('FERIE_CHRETIEN', 'Férié chrétien'), ('FERIE_MUSULMAN', 'Férié musulman'), ('FERIE_CIVIL', 'Férié civil'), ('FERIE_INTERNE', 'Férié interne'), ('FERIE_AUTRE', 'Autre')], default='FERIE_CIVIL', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_ATTENTE', 'En attente')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('est_modifie', models.BooleanField(default=False, verbose_name='Date modifiée')),
                ('est_personnalise', models.BooleanField(default=False, verbose_name='Personnalisé')),
                ('est_national', models.BooleanField(default=True, verbose_name='National')),
                ('est_paye', models.BooleanField(default=True, verbose_name='Chômé payé')),
                ('code_pays', models.CharField(default='CI', max_length=2, verbose_name='Code pays')),
                ('cree_par', models.CharField(blank=True, max_length=100, null=True, verbose_name='Créé par')),
                ('modifie_par', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modifié par')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jours_feries', to='mainapp.modelejourferie', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'jours_feries',
                'ordering': ['annee', 'date_ferie'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('RESTAURATION', 'Restauration')], max_length=20)),
                ('champ_modifie', models.CharField(blank=True, max_length=50, null=True)),
                ('ancienne_valeur', models.TextField(blank=True, null=True)),
                ('nouvelle_valeur', models.TextField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('effectue_par', models.CharField(blank=True, max_length=100, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('jour_ferie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='mainapp.jourferie', verbose_name='Jour férié')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historique des modifications',
                'db_table': 'historique_modifications_feries',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='jourferie',
            index=models.Index(fields=['date_ferie'], name='idx_date_ferie'),
        ),
        migrations.AddIndex(
            model_name='jourferie',
            index=models.Index(fields=['annee'], name='idx_annee'),
        ),
        migrations.AddIndex(
            model_name='jourferie',
            index=models.Index(fields=['code_pays', 'annee'], name='idx_pays_annee'),
        ),
        migrations.AddConstraint(
            model_name='jourferie',
            constraint=models.UniqueConstraint(condition=models.Q(('modele__isnull', False)), fields=('modele', 'annee', 'code_pays'), name='uq_modele_annee_pays'),
        ),
        migrations.AddConstraint(
            model_name='jourferie',
            constraint=models.UniqueConstraint(fields=('date_ferie', 'code_pays'), name='uq_date_ferie_pays'),
        ),
        migrations.AddConstraint(
            model_name='jourferie',
            constraint=models.UniqueConstraint(fields=('nom', 'annee', 'code_pays'), name='uq_nom_annee_pays'),
        ),
    ]
