# Generated by Django 4.2.21 on 2025-12-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_modelejourferie_jourferie_historiquemodification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementDateFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suggeree', models.DateField(verbose_name='Date suggérée')),
                ('source_info', models.CharField(max_length=255, verbose_name="Source de l'information")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Date du signalement')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('jour_ferie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='mainapp.jourferie', verbose_name='Jour férié')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_feries', to='mainapp.profilutilisateur', verbose_name='Signalé par')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='mainapp.profilutilisateur', verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Signalement de date',
                'verbose_name_plural': 'Signalements de dates',
                'db_table': 'signalements_dates_feries',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
