# Generated by Django 4.2.21 on 2026-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_signalementdateferie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationapikelio',
            name='password',
        ),
        migrations.AddField(
            model_name='configurationapikelio',
            name='password_encrypted',
            field=models.CharField(blank=True, default='', help_text="Mot de passe crypté (ne s'affiche pas en clair)", max_length=500),
        ),
    ]
